// question 1

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Users[
    <!ELEMENT Users(Users+)>
    <!ELEMENT User(Name, Hobby+, Address)>
    <!ELEMENT Name(#PCDATA)>
    <!ELEMENT Hobby(#PCDATA)>
    <!ELEMENT Address(District.Location)>
    <!ELEMENT District(#PCDATA)>
    <!ELEMENT Location(#PCDATA)>
    <!ATTLIST User country CDATA #REQUIRED>
]>

    <Users>
     <User country="Nepal">
        <Name>Anish Sharma</Name>
        <Hobby>Football<Hobby>
            <Address>
                <District>Lalitpur</District>
                <Location>Kumaripati</District>
            </Address>
        </User>
            <User country="Nepal">
                <Name>Sugam Poudel</Name>
                <Hobby>Cricket</Hobby>
                <Address>
                    <District>Kathmandu</District>
                    <Location>Gongabu</Location>
                </Address>
            </User>
        <Users>